version: '3'
services:
 webapp:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     PORT: 80
   ports:
     - "8080:80"
 db:
  image: postgres:15.4-alpine3.18
  environment:
    POSTGRES_PASSWORD: 123456
    POSTGRES_DB: db
