version: '3.4'
services:
 webapp:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     PORT: 80
     DB_USER: "postgres"
     DB_PASSWORD: "123456"
     DB_HOST: "db:5432"
     DB_NAME: "postgres"
   ports:
     - "8080:80"
   depends_on:
     db:
       condition: service_healthy
 db:
  image: postgres:15.4-alpine3.18
  environment:
    POSTGRES_PASSWORD: "123456"
  ports:
    - "5432:5432"
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
    interval: 20s
    timeout: 60s
    retries: 5
    start_period: 20s